fix reading of readme
On some environments, the setup.py is unable to complete due to encoding
issues. Use vanialla python open() to rely on the python encoding abilities.

    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-986m_f7j/sacred/setup.py", line 46, in <module>
        long_description=Path("README.rst").read_text(),
      File "/usr/lib/python3.6/pathlib.py", line 1197, in read_text
        return f.read()
      File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 10799: ordinal not in range(128)